version: "3"
services:
  file-code-box:
    image: lw11/filecodebox:latest
    volumes:
      - fcb-data:/app/data:rw
    restart: unless-stopped
    ports:
      - "2222:2222"
volumes:
  fcb-data:
    external: false